# Generated by Django 5.2.13 on 2026-04-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bayse_event_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "bayse_market_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("crypto", "Cryptocurrency"),
                            ("sports", "Sports"),
                            ("politics", "Politics"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "implied_probability",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "volume_24h",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "liquidity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=10)),
                (
                    "signal_potential_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-signal_potential_score", "-volume_24h"],
                "indexes": [
                    models.Index(
                        fields=["status", "category"],
                        name="markets_mar_status_9db0cb_idx",
                    ),
                    models.Index(
                        fields=["signal_potential_score"],
                        name="markets_mar_signal__c36efd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuantMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("momentum_score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("momentum_direction", models.CharField(max_length=20)),
                (
                    "price_change_1h",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "price_change_6h",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "volume_acceleration",
                    models.DecimalField(decimal_places=4, max_digits=6),
                ),
                ("volume_trend", models.CharField(max_length=20)),
                ("bid_ask_spread", models.DecimalField(decimal_places=6, max_digits=6)),
                ("order_book_bias", models.CharField(max_length=20)),
                (
                    "bid_depth",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ask_depth",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quant_metrics",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quant metrics",
                "ordering": ["-calculated_at"],
                "get_latest_by": "calculated_at",
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Price history",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["market", "timestamp"],
                        name="markets_pri_market__d87867_idx",
                    )
                ],
            },
        ),
    ]
