# Generated by Django 5.2.13 on 2026-04-17 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("min_edge_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "min_momentum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "max_spread",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=6, null=True
                    ),
                ),
                ("min_confidence", models.IntegerField(blank=True, null=True)),
                ("categories", models.JSONField(default=list)),
                (
                    "max_stake_per_trade",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("use_kelly", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Backtest strategies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "initial_bankroll",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("total_trades", models.IntegerField()),
                ("winning_trades", models.IntegerField()),
                ("losing_trades", models.IntegerField()),
                ("win_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_return", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_return_pct",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "final_bankroll",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("max_drawdown", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_drawdown_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("trade_log", models.JSONField(default=list)),
                ("ai_review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="backtesting.backteststrategy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
