# Generated by Django 5.2.13 on 2026-04-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("WAIT", "Wait")],
                        max_length=10,
                    ),
                ),
                ("edge_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "expected_value",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "market_probability",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("ai_probability", models.DecimalField(decimal_places=2, max_digits=5)),
                ("confidence", models.IntegerField()),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Low (0-40%)"),
                            ("medium", "Medium (40-70%)"),
                            ("high", "High (70-100%)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kelly_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "recommended_stake_conservative",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "recommended_stake_balanced",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "recommended_stake_aggressive",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("reasoning", models.TextField()),
                ("news_context", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("signal_strength", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-edge_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimated_probability",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("confidence_score", models.IntegerField()),
                ("reasoning_summary", models.TextField()),
                ("sources_consulted", models.TextField(blank=True)),
                (
                    "model_used",
                    models.CharField(default="gemini-flash-latest", max_length=50),
                ),
                ("search_grounding_used", models.BooleanField(default=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="markets.market",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="signals.signal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AI analyses",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["is_active", "edge_score"],
                name="signals_sig_is_acti_efa13e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["direction", "created_at"],
                name="signals_sig_directi_b65ff6_idx",
            ),
        ),
    ]
