# Generated by Django 5.2.13 on 2026-04-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='model_used',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
    ]
